#!/bin/bash

set -e

if [ "$#" -ne "1" ]
then
  echo "Usage: $0 [up/down]"
  exit 1
fi

root=/sys/class/backlight/intel_backlight

function current() {
  max=$(cat "$root/max_brightness")
  current=$(cat "$root/brightness")
  echo $(("$current" * 100 / "$max"))
}

function update() {
  max=$(cat "$root/max_brightness")
  modified=$(("$1" * "$max" / 100))
  if [ "$1" -gt 100 ]
  then
    modified="$max"
  fi
  if [ "$1" -lt 5 ]
  then
    modified=$(("$max" / 20))
  fi
  echo "$modified" | sudo tee "$root/brightness"
}

if [ "$1" == "up" ]
then
  now=$(current)
  update $(("$now" + 5))
  exit 0
fi

if [ "$1" == "down" ]
then
  now=$(current)
  update $(("$now" - 5))
  exit 0
fi

echo "Invalid argument \"$1\""
exit 1
