#!/bin/bash

if [ -z "$1" ]
then
  echo "Usage: $0 [repo_name]"
  exit 1
fi

repo="/srv/git/$1.git"
if [ -d "$repo" ]
then
  echo "Repository exists"
  exit 1
fi

mkdir "$repo" &&
  cd "$repo" &&
  git init --bare &&
  chown -R git:git "$repo" ||
  rm -rf "$repo"

clone=$(mktemp -d)
cd "$clone" &&
  touch .gitignore &&
  git init &&
  git add . &&
  git config user.name 'gitbot' &&
  git config user.email 'gitbot@localhost' &&
  git commit -m 'Initial commit' &&
  git remote add origin "$repo" &&
  git push origin master ||
  rm -rf "$repo"

rm -rf "$clone"
test -f "$repo/.gitignore" &&
  exit 0 ||
  exit 1
