#!/bin/bash

address='http://someonewhocares.org/hosts/hosts'
marker='Last updated'

function version
{
  curl -s "$address" |
  while read line
  do
    if [[ "$line" =~ "$marker" ]]
    then
      echo "$line"
      exit
    fi
  done
}

current=$(sed "/$marker/!d" < /etc/hosts)
[ "$current" == "$(version)" ] && exit
curl -s "$address" | sudo tee /etc/hosts > /dev/null
